name: Run External Action and Handle Failure

on:
  push:
    branches:
      - main

jobs:
  run-external-action:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run External Action
        id: external-action
        uses: ./.github/actions/external-action
        with:
          input-parameter: 'default-value' # Replace with your desired input

      - name: Check if External Action Succeeded
        if: steps.external-action.outcome == 'failure'
        run: |
          echo "External Action failed. Stopping workflow."
          exit 1

      - name: Continue if External Action Succeeded
        if: steps.external-action.outcome == 'success'
        run: |
          echo "External Action succeeded. Continuing workflow."
