name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  primary-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      # First, run the other workflow file
      - name: Run Other Workflow
        uses: ./.github/workflows/build_with_proxy.yml
        id: other-workflow
        continue-on-error: true  # This allows us to check the outcome
      
      # Only continue if the other workflow succeeded
      - name: Continue if previous workflow succeeded
        if: steps.other-workflow.outcome == 'success'
        run: |
          echo "Other workflow succeeded, continuing with next steps..."
          # Add your additional steps here
          
      # Stop if the other workflow failed
      - name: Stop if previous workflow failed
        if: steps.other-workflow.outcome != 'success'
        run: |
          echo "Other workflow failed, stopping execution"
          exit 1
